/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package it.unibo.yahm

import io.reactivex.rxjava3.schedulers.Schedulers
import it.unibo.yahm.client.sensors.*

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    val thread = Schedulers.newThread()

//    ReactiveSensor().observer(SensorType.ACCELEROMETER).observeOn(thread).subscribe {
//        println(Acceleration.fromSensorEvent(it))
//    }
//
//    ReactiveSensor().observer(SensorType.GYROSCOPE).observeOn(thread).subscribe {
//        println(AngularVelocity.fromSensorEvent(it))
//    }

    ReactiveLocation().observe().observeOn(thread).subscribe {
        println(it)
    }

    Thread.sleep(100000)



    println(App().greeting)

}
